# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    #valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        product_thumb:
            quality: 80
            filters:
                thumbnail: { size: [250, 190], mode: inset, allow_upscale: true }
                background: { size: [250, 190], position: center, color: '#ffffff' }

        product_thumb_01:
            quality: 80
            filters:
                thumbnail: { size: [350, 240], mode: inset, allow_upscale: false }
                background: { size: [350, 240], position: center, color: '#ffffff' }