version: '3.3'
services:
  ecom_nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - .:/var/www/html
      - ./docker/nginx/logs:/var/log/nginx
      - /tmp:/tmp
    links:
      - ecom_php

  ecom_php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
      - ~/.composer:/var/www/.composer
    links:
      - ecom_mysql

  ecom_mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecom902
      - MYSQL_USER=roman
      - MYSQL_PASSWORD=2508igor
    volumes:
      - ecom_mysql_data:/var/lib/mysql

volumes:
  ecom_mysql_data:
